import type { KegiatanContent } from '../types';

export const kegiatan4: KegiatanContent = {
  nomor: 4,
  judul: 'Kegiatan 4 — Bagaimana Menghasilkan Biodiesel dengan Kualitas Optimal secara Cepat?',
  subjudul: 'Pengaruh Katalis terhadap Laju Reaksi',
  warna: '#00695C',
  warnaLight: '#E0F2F1',
  sdg: [
    { nomor: 7, warna: '#FCC30B', label: 'Energi Bersih & Terjangkau' },
    { nomor: 13, warna: '#3F7E44', label: 'Aksi Iklim' },
  ],
  cakupanMateri: [
    'Faktor yang memengaruhi laju reaksi (katalis)',
    'Hukum laju dan orde reaksi',
    'Tetapan laju reaksi (k)',
    'Energi aktivasi',
    'Teori tumbukan',
    'Analisis efisiensi',
  ],
  tujuan: [
    'Menjelaskan pengaruh katalis terhadap laju reaksi berdasarkan teori tumbukan.',
    'Menganalisis dan menentukan persamaan laju reaksi.',
    'Menghitung tetapan laju reaksi (k).',
    'Menganalisis efisiensi penggunaan katalis berdasarkan data laju reaksi.',
    'Menyusun argumentasi ilmiah mengenai efisiensi penggunaan katalis.',
  ],
  materi:
    'Katalis mempercepat laju reaksi dengan menurunkan energi aktivasi, sehingga lebih banyak partikel memiliki energi melebihi ambang batas untuk ber-tumbukan efektif. Katalis tidak ikut bereaksi dan dapat digunakan kembali.',
  steps: [
    {
      id: 's1',
      sintaks: 1,
      label: 'Orientasi pada Masalah',
      ringkas: 'Stimulus, narasi masalah & pertanyaan pemantik',
      blocks: [
        {
          kind: 'stimulus',
          title: 'Amati dan Simak',
          body: 'Video proses transesterifikasi minyak jelanta menjadi biodiesel. Gambar pengamatan: reaksi dengan katalis berlangsung lebih cepat dibandingkan tanpa katalis. Artikel pendukung: program B35 Indonesia dan pemanfaatan minyak jelanta sebagai bahan baku biodiesel.',
        },
        {
          kind: 'masalah',
          title: 'Narasi Masalah',
          body: 'Industri biodiesel menggunakan minyak jelanta sebagai bahan baku melalui reaksi transesterifikasi. Untuk mempercepat reaksi, digunakan katalis NaOH. Namun penggunaan katalis berlebihan dapat meningkatkan biaya dan menghasilkan sabun sebagai produk sampingan yang sulit dipisahkan. Bagaimana menentukan jumlah katalis yang paling efisien?',
        },
        { kind: 'pertanyaan', id: 'k4_p1', text: 'Mengapa katalis digunakan dalam reaksi transesterifikasi?' },
        { kind: 'pertanyaan', id: 'k4_p2', text: 'Bagaimana katalis memengaruhi laju reaksi?' },
        { kind: 'pertanyaan', id: 'k4_p3', text: 'Bagaimana menentukan jumlah katalis yang efisien agar tidak menimbulkan dampak lingkungan tambahan?' },
      ],
    },
    {
      id: 's2',
      sintaks: 2,
      label: 'Mengorganisasi Peserta Didik',
      ringkas: 'Diagnosis awal & perencanaan penyelidikan',
      blocks: [
        {
          kind: 'tabel-org',
          id: 'k4_org',
          headers: ['Apa yang sudah diketahui?', 'Apa yang perlu diketahui?', 'Hipotesis'],
          rowCount: 3,
          title: 'Aktivitas 1 — Diagnosis Awal',
          perencanaanId: 'k4_rencana',
          perencanaanText: 'Aktivitas 2 — Perencanaan Penyelidikan: Tuliskan informasi yang perlu dikumpulkan agar dapat menentukan jumlah katalis yang paling efisien.',
        },
      ],
    },
    {
      id: 's3',
      sintaks: 3,
      label: 'Membimbing Penyelidikan',
      ringkas: 'Data percobaan, orde reaksi & efisiensi',
      blocks: [
        { kind: 'bagian-header', label: 'Bagian A — Analisis Data Eksperimen' },
        {
          kind: 'data-eksperimen',
          title: 'Percobaan transesterifikasi minyak jelanta dengan variasi konsentrasi katalis NaOH',
          headers: ['Konsentrasi katalis (M)', 'Waktu konversi (menit)', 'Laju konversi (%/menit)'],
          rows: [['0,5', '45', '2,22'], ['1,0', '30', '3,33'], ['1,5', '20', '5,0']],
        },
        { kind: 'input-hitung', id: 'k4_h1', label: 'Hitung laju konversi pada masing-masing konsentrasi katalis', unit: '%/menit', allowImage: true },
        { kind: 'analitis', id: 'k4_h2', text: 'Buat grafik hubungan konsentrasi katalis terhadap laju konversi.', allowImage: true },
        { kind: 'analitis', id: 'k4_h3', text: 'Berdasarkan data, bagaimana hubungan konsentrasi katalis dengan laju reaksi?' },
        { kind: 'input-hitung', id: 'k4_h4', label: 'Tentukan orde reaksi terhadap katalis', allowImage: true },
        { kind: 'input-hitung', id: 'k4_h5', label: 'Tuliskan persamaan laju reaksi' },
        { kind: 'input-hitung', id: 'k4_h6', label: 'Hitung nilai tetapan laju reaksi (k), lengkap dengan satuannya', allowImage: true },
        { kind: 'input-hitung', id: 'k4_h7', label: 'Prediksi laju reaksi jika konsentrasi katalis dinaikkan menjadi 2,0 M' },
        { kind: 'bagian-header', label: 'Bagian B — Penalaran Kimia (Representasi Submikroskopik)' },
        {
          kind: 'diagram-submikro',
          title: 'Kurva energi aktivasi: tanpa katalis vs dengan katalis',
          kiri: { label: 'Tanpa Katalis', deskripsi: 'Energi aktivasi tinggi → sedikit partikel melebihi ambang → reaksi lambat.' },
          kanan: { label: 'Dengan Katalis', deskripsi: 'Energi aktivasi rendah → banyak partikel melebihi ambang → reaksi cepat.' },
        },
        { kind: 'analitis', id: 'k4_b1', text: 'Mengapa katalis dapat mempercepat laju reaksi?' },
        { kind: 'analitis', id: 'k4_b2', text: 'Bagaimana katalis menurunkan energi aktivasi?' },
        { kind: 'analitis', id: 'k4_b3', text: 'Bagaimana teori tumbukan menjelaskan pengaruh katalis terhadap laju reaksi?' },
        { kind: 'bagian-header', label: 'Bagian C — Analisis Efisiensi' },
        {
          kind: 'analisis-efisiensi',
          id: 'k4_ef',
          title: 'Tiga pilihan konsentrasi katalis untuk skala produksi',
          headers: ['Konsentrasi', 'Efektivitas', 'Biaya & Dampak'],
          rows: [['0,5 M', 'Sedang', 'Rendah'], ['1,0 M', 'Tinggi', 'Sedang'], ['1,5 M', 'Sangat tinggi', 'Tinggi (sabun sampingan)']],
          pertanyaanId: 'k4_ef_jwb',
          pertanyaanText: 'Apakah peningkatan konsentrasi katalis selalu sebanding dengan manfaat yang diperoleh? Jelaskan berdasarkan hasil analisis data pada tabel di atas serta hasil perhitungan pada Bagian A.',
        },
      ],
    },
    {
      id: 's4',
      sintaks: 4,
      label: 'Mengembangkan dan Menyajikan Hasil',
      ringkas: 'Peran konsultan energi terbarukan & unggah karya',
      blocks: [
        {
          kind: 'instruksi-pengembangan',
          title: 'Peran: Konsultan Energi Terbarukan',
          body: 'Setiap kelompok berperan sebagai konsultan energi terbarukan yang diminta menyusun rekomendasi kepada industri biodiesel mengenai konsentrasi katalis yang paling efisien. Presentasi memuat:',
          bullets: [
            'Hasil perhitungan laju konversi.',
            'Grafik hubungan konsentrasi katalis terhadap laju reaksi.',
            'Persamaan laju reaksi dan tetapan laju (k).',
            'Prediksi laju reaksi pada konsentrasi baru.',
            'Alasan ilmiah di balik rekomendasi.',
            'Rekomendasi penggunaan katalis yang paling efisien.',
          ],
        },
        { kind: 'upload-hasil', id: 'k4_up', title: 'Unggah Karya', body: 'Unggah bahan presentasi kelompok Anda pada kolom yang tersedia.' },
      ],
    },
    {
      id: 's5',
      sintaks: 5,
      label: 'Menganalisis dan Mengevaluasi',
      ringkas: 'Studi kasus, alternatif & argumentasi TAP',
      blocks: [
        {
          kind: 'alternatif-kasus',
          id: 'k4_alt',
          title: 'Studi Kasus — Industri ingin meningkatkan produksi biodiesel. Pilih alternatif paling tepat:',
          options: [
            { id: 'a', label: 'Alternatif A', deskripsi: 'Menggunakan katalis sebanyak-banyaknya agar reaksi secepat mungkin.' },
            { id: 'b', label: 'Alternatif B', deskripsi: 'Menggunakan katalis sesedikit mungkin agar biaya murah.' },
            { id: 'c', label: 'Alternatif C', deskripsi: 'Menggunakan konsentrasi katalis optimum berdasarkan hasil analisis laju reaksi sehingga proses tetap efektif, biaya terkendali, dan dampak lingkungan dapat diminimalkan.' },
          ],
          alasanId: 'k4_alt_alasan',
        },
        {
          kind: 'argumentasi-tap',
          id: 'k4_tap',
          title: 'Argumentasi Ilmiah (TAP)',
          kasus: 'Berdasarkan hasil analisis laju reaksi dan efisiensi penggunaan katalis, alternatif manakah yang paling tepat? Susun argumentasimu dengan kerangka TAP.',
        },
        {
          kind: 'penalaran-level',
          makroskopik: 'Proses transesterifikasi minyak jelanta menjadi biodiesel.',
          submikroskopik: 'Ilustrasi energi aktivasi dengan dan tanpa katalis serta jumlah partikel yang melebihi ambang energi.',
          simbolik: 'Tabel data eksperimen, perhitungan laju konversi, persamaan laju, dan tetapan laju.',
        },
      ],
    },
  ],
};
